version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./.env
  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:dev auth
  api:
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:dev server
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - '15432:80'
